### ISSUE TITLE
Determine cost to run website

### ISSUE THREAD

**Issue by timbroadwater** [usergoodness/usergoodness.github.io#87]

**Comment by timbroadwater** [comment]
Prices are based on GoDaddy, are annual, and include tax:

- $31.46 - .COM, .INFO, .NET, and .ORG Domain Names
- $101.63 - Economy Package (1 website, Unmetered bandwidth, 1 year free Office 365)
- $63.47 - Office 365 for one year
- $63.58 - Secures one website, Strong SHA2 & 2048-bit encryption, Boosts your site’s Google ranking, McAfee SECURE trustmark 
---------------------------------------
- **$260.16** TOTAL

**Comment by kevikramer** [comment]
We could start with my hosting with asmallorange- it would only be $43 per year since I run my portfolio on that hosting too. 50gb monthly bandwidth should be plenty to start.

**Comment by timbroadwater** [comment]
I have free hosting too.., where it is now, but I think the goal is to price it all out, and see what it costs.
